export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_FAILED = 'UPDATE_FAILED';
export const LOADING_USER= 'LOADING';

export const ALL_SUCCESS = 'GET ALL USERS SUCCESS';
export const ALL_FAILED = 'GET ALL USERS FAILED';
export const LOADING_USERS= 'LOADING USERS';
